server.port:8089

#Mongo DB connections
spring.data.mongodb.uri=mongodb+srv://kanchanya:9ZUZzLLMxKSs@cluster0.gnzlelx.mongodb.net/AccountDB?retryWrites=true&w=majority&appName=Cluster0

#Actuator-cloudwatch
management.metrics.export.cloudwatch.enabled=true
management.metrics.export.cloudwatch.namespace=AccountServiceMetrics
management.metrics.export.cloudwatch.step=1m
management.metrics.export.cloudwatch.batchsize=20

